# Generated by Django 5.1.3 on 2024-11-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rpi_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device_ip', models.CharField(max_length=200)),
                ('device_type', models.CharField(max_length=200)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_set', to='playgrounds.playground')),
            ],
        ),
    ]
