# Generated by Django 5.1.3 on 2024-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playground',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
