# Generated by Django 5.1.3 on 2024-11-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0002_remove_device_id_device_device_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_ip',
            new_name='deviceIp',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_type',
            new_name='deviceType',
        ),
    ]
